# Generated by Django 3.0.3 on 2020-04-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=500)),
                ('state', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('close_date', models.DateField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modify', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Fb_Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_lg_token', models.CharField(max_length=180)),
                ('app_secret_key', models.CharField(max_length=30)),
                ('app_id', models.CharField(max_length=20)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('data', models.FileField(upload_to='')),
                ('description', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('poste_date', models.DateField()),
                ('poste_heure', models.TimeField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Campagne')),
            ],
        ),
        migrations.CreateModel(
            name='Fb_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('page_id', models.CharField(max_length=30)),
                ('page_lg_tk', models.CharField(max_length=180)),
                ('fb_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Fb_Access')),
            ],
        ),
    ]
