# Generated by Django 3.0.3 on 2020-04-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectif',
            name='data',
            field=models.CharField(max_length=150),
        ),
    ]
