# Generated by Django 3.0.3 on 2020-07-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fb_post_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
