# Generated by Django 3.0.3 on 2020-04-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data_file',
        ),
    ]
