# Generated by Django 3.0.3 on 2020-04-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200409_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectif',
            name='data',
        ),
    ]
