# Generated by Django 3.0.3 on 2020-04-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_objectif_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='objectif',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
