# Generated by Django 3.0.3 on 2020-04-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200423_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
